import { connectDB } from "./db.js";
import Client from "./models/Client.js";

const CLIENTS = [
  {
    id:"fb", name:"FreshBite Foods", init:"FB",
    website:"freshbitefoods.com", faavi:72,
    phase:"bau", pkg:"Growth", consultant:"Priya Nair",
    auditAge:18, lastScanned:"Today, 09:14",
    confidence:"high",
    profile:{
      type:"D2C · FMCG",
      industry:"Food & Beverage",
      subIndustry:"Packaged Snacks & Health Foods",
      model:"Direct-to-consumer packaged snack brand. Revenue via own website, quick-commerce (Zepto, Swiggy Instamart), and modern trade.",
      stage:"Series A",
      founded:"2019",
      employees:"50–200",
      geography:"Pan-India. Primary: South & West. Expanding: North.",
      market:"Urban Tier-1 and Tier-2 cities. Health-conscious consumers. Rising demand for better-for-you snacking alternatives.",
    },
    personas:[
      "Health-conscious millennials, 22–35, urban metros",
      "Fitness enthusiasts seeking low-sugar snack options",
      "Working professionals needing guilt-free desk snacks",
      "Parents buying healthier alternatives for children",
    ],
    competitors:{
      direct:     ["Too Yumm", "Happilo", "Yoga Bar", "UNIBIC"],
      indirect:   ["Haldiram's", "Lay's Baked", "Britannia NutriChoice"],
      aspirational:["Kind Bars", "RXBar", "Graze"],
    },
    products:["Millet snacks", "Low-sugar biscuits", "Protein bars", "Roasted seeds mix", "Snack subscription box"],
    channels:{
      aeo:     { score:68, benchmark:52, trend:+4, gaps:3,  benchmarkSrc:"Category avg" },
      seo:     { score:74, benchmark:61, trend:+2, gaps:2,  benchmarkSrc:"Category avg" },
      meo:     { score:80, benchmark:55, trend: 0, gaps:1,  benchmarkSrc:"Local avg"    },
      ai:      { score:58, benchmark:48, trend:+8, gaps:4,  benchmarkSrc:"Category avg" },
      reviews: { score:85, benchmark:60, trend:+3, gaps:1,  benchmarkSrc:"Category avg" },
      social:  { score:62, benchmark:55, trend:-1, gaps:2,  benchmarkSrc:"Category avg" },
    },
    issues:[
      { id:"i1", channel:"AEO", title:"No FAQ schema on any of the 14 product pages", priority:24.0, impact:9, effort:1, confidence:9, why:"Featured snippets and AI answer boxes are captured via structured data. Without schema, FreshBite cannot win these placements regardless of content quality. Competitors with schema own the top of SERP." },
      { id:"i2", channel:"AI",  title:"Brand not cited in ChatGPT or Gemini for 'best healthy snacks India'", priority:21.0, impact:9, effort:3, confidence:8, why:"Consumers increasingly trust AI recommendations as purchasing signals. Absence here means the brand is invisible at a high-intent decision moment. Competitors Yoga Bar and Happilo are actively cited." },
      { id:"i3", channel:"SEO", title:"3 high-volume content cluster pages missing (combined 38K/mo)", priority:14.4, impact:8, effort:5, confidence:9, why:"Content gaps directly translate to traffic lost to competitors. Each page represents a compounding organic asset. Delay increases competitor authority in these queries." },
      { id:"i4", channel:"MEO", title:"2 distribution partner branches unclaimed on Google Maps", priority:12.0, impact:6, effort:2, confidence:8, why:"Unclaimed GBP listings allow competitors to appear alongside brand touchpoints. Also affects local search ranking and AI systems that source location data from Maps." },
      { id:"i5", channel:"AI",  title:"No structured comparison pages to trigger AI citation", priority:10.5, impact:7, effort:4, confidence:6, why:"AI systems heavily cite comparison and category pages. FreshBite has product pages but no 'FreshBite vs X' or 'best snacks for Y' content that AI systems pull from." },
    ],
    openRecs:3, openTasks:1, activeProjects:3,
  },
  {
    id:"nb", name:"NutriBlend India", init:"NB",
    website:"nutriblend.in", faavi:61,
    phase:"launch", pkg:"Growth", consultant:"Priya Nair",
    auditAge:42, lastScanned:"42 days ago",
    confidence:"medium",
    profile:{
      type:"D2C · Health & Wellness",
      industry:"Nutrition & Supplements",
      subIndustry:"Sports Nutrition / Protein",
      model:"Direct-to-consumer protein and nutrition supplements. Revenue via own website and Amazon India. Gym and fitness community as primary acquisition channel.",
      stage:"Seed",
      founded:"2021",
      employees:"20–50",
      geography:"Pan-India, primarily gym-dense urban centres.",
      market:"Growing sports nutrition market driven by fitness adoption post-2020. Under-served mid-price segment between mass brands and premium imports.",
    },
    personas:[
      "Gym-goers and recreational athletes, 20–35",
      "Women entering fitness — seeking non-intimidating protein options",
      "Weight management seekers looking for high-protein diet support",
      "Athletes seeking performance nutrition without imports",
    ],
    competitors:{
      direct:      ["MuscleBlaze", "Myprotein India", "Fast&Up", "AS-IT-IS Nutrition"],
      indirect:    ["Epigamia Greek Yoghurt", "RiteBite", "Sattu-based brands"],
      aspirational:["Optimum Nutrition", "Dymatize", "Garden of Life"],
    },
    products:["Whey protein isolate", "Plant protein blend", "Multivitamins", "Pre-workout formula", "Protein snack bars"],
    channels:{
      aeo:     { score:52, benchmark:52, trend:+3, gaps:5,  benchmarkSrc:"Category avg" },
      seo:     { score:65, benchmark:61, trend:+1, gaps:4,  benchmarkSrc:"Category avg" },
      meo:     { score:55, benchmark:45, trend: 0, gaps:2,  benchmarkSrc:"N/A — online only" },
      ai:      { score:48, benchmark:48, trend:-2, gaps:6,  benchmarkSrc:"Category avg" },
      reviews: { score:70, benchmark:60, trend:+1, gaps:3,  benchmarkSrc:"Category avg" },
      social:  { score:55, benchmark:55, trend:+2, gaps:3,  benchmarkSrc:"Category avg" },
    },
    issues:[
      { id:"i1", channel:"AI",  title:"Brand completely absent from all AI platform responses for category queries", priority:24.0, impact:9, effort:3, confidence:8, why:"NutriBlend ranks on Google but AI systems (ChatGPT, Perplexity, Gemini) do not cite it for 'best protein powder India' or related queries. This gap will widen as AI search share grows. Competitor MuscleBlaze is cited in all 3 platforms." },
      { id:"i2", channel:"SEO", title:"Domain authority (DA 18) critically below competitors — MuscleBlaze DA 52, Myprotein DA 61", priority:18.0, impact:8, effort:5, confidence:9, why:"Low DA means FreshBite cannot compete for competitive keywords regardless of content quality. Each month of delay is a compounding disadvantage as competitors build more links." },
      { id:"i3", channel:"AEO", title:"Competitor owns AI answer for 'best protein powder without side effects' (8.2K/mo)", priority:15.0, impact:8, effort:3, confidence:7, why:"This is a high-purchase-intent query. The competitor article ranking here captures users at peak buying readiness. NutriBlend has no equivalent page." },
      { id:"i4", channel:"Reviews", title:"Amazon reviews averaging 3.8★ — below 4.0★ conversion threshold", priority:9.6, impact:8, effort:4, confidence:6, why:"Research shows conversion drops sharply below 4.0★. NutriBlend's Amazon performance is directly limited by review score. 50 targeted review requests could move this to 4.2★." },
    ],
    openRecs:5, openTasks:4, activeProjects:2,
  },
  {
    id:"ch", name:"CraftHome Decor", init:"CH",
    website:"crafthomedecor.com", faavi:53,
    phase:"audit", pkg:"Starter", consultant:"Vikram Das",
    auditAge:67, lastScanned:"67 days ago",
    confidence:"low",
    profile:{
      type:"D2C · E-commerce",
      industry:"Home Decor & Lifestyle",
      subIndustry:"Handcrafted & Artisanal Home Products",
      model:"Online-first home decor. Revenue via own website and offline showroom (Bengaluru). Seasonal gifting and corporate orders are significant revenue contributors.",
      stage:"Bootstrapped",
      founded:"2018",
      employees:"10–50",
      geography:"Primarily Bengaluru. Online reach pan-India. International orders via Etsy (nascent).",
      market:"Premium handcrafted home decor. Underserved segment between mass-market (Pepperfry) and luxury. Growing demand for artisan products, sustainability narrative.",
    },
    personas:[
      "Homemakers and interior design enthusiasts, 28–45, urban metros",
      "Corporate gifting decision-makers (HR, admin teams)",
      "Wedding planners and event decorators",
      "NRI buyers seeking authentic Indian artisan products",
    ],
    competitors:{
      direct:      ["Pepperfry", "Urban Ladder", "WoodenStreet"],
      indirect:    ["Fabindia Home", "Good Earth", "Nappa Dori"],
      aspirational:["Crate & Barrel", "CB2", "Anthropologie Home"],
    },
    products:["Handmade wall art", "Furniture accents", "Festive décor", "Custom name boards", "Corporate gift boxes"],
    channels:{
      aeo:     { score:41, benchmark:52, trend:-2, gaps:6,  benchmarkSrc:"Category avg" },
      seo:     { score:58, benchmark:61, trend:+1, gaps:5,  benchmarkSrc:"Category avg" },
      meo:     { score:48, benchmark:55, trend: 0, gaps:4,  benchmarkSrc:"Local avg"    },
      ai:      { score:38, benchmark:48, trend:-5, gaps:7,  benchmarkSrc:"Category avg" },
      reviews: { score:63, benchmark:60, trend:-1, gaps:3,  benchmarkSrc:"Category avg" },
      social:  { score:58, benchmark:55, trend:+3, gaps:2,  benchmarkSrc:"Category avg" },
    },
    issues:[
      { id:"i1", channel:"MEO", title:"Physical showroom unclaimed on Google Maps — invisible to local search", priority:32.0, impact:8, effort:1, confidence:9, why:"Local search is the primary discovery mechanism for offline retail. An unclaimed GBP listing means competitors appear where CraftHome should. Maps data also feeds AI local recommendations. 15-minute fix with potentially months of compounding benefit." },
      { id:"i2", channel:"AEO", title:"'Home decor ideas' and related queries (110K/mo combined) — zero content targeting these", priority:27.0, impact:9, effort:4, confidence:8, why:"Home decor is a heavily searched category. Competitors Pepperfry and Urban Ladder dominate these queries with content hubs. CraftHome has product pages but no inspirational or informational content that captures top-of-funnel intent." },
      { id:"i3", channel:"AI",  title:"Brand completely absent from AI recommendations in home decor category", priority:21.6, impact:9, effort:5, confidence:8, why:"AI recommendation absence is most damaging in discovery categories where consumers ask 'what should I buy'. Home decor is exactly this. CraftHome's competitors are cited; the brand is not." },
      { id:"i4", channel:"Reviews", title:"0% review response rate — 17 unanswered reviews including 3 negative", priority:16.0, impact:8, effort:2, confidence:9, why:"Unanswered negative reviews are one of the highest-trust-cost items in local search. Google uses review response rate as a GBP quality signal. Unanswered reviews also signal to AI systems that the business is inactive." },
      { id:"i5", channel:"SEO", title:"'Minimalist home decor' (74K/mo) tracked at position 28 — no dedicated page", priority:14.4, impact:8, effort:5, confidence:9, why:"Ranking 28th means effectively no organic traffic (CTR at position 28 < 0.5%). A single well-built landing page targeting this query cluster could reach top 10 within 90 days based on competition analysis." },
    ],
    openRecs:8, openTasks:6, activeProjects:1,
  },
  {
    id:"df", name:"DermFirst", init:"DF",
    website:"dermfirst.in", faavi:68,
    phase:"campaigns", pkg:"Enterprise", consultant:"Vikram Das",
    auditAge:9, lastScanned:"Today, 11:30",
    confidence:"high",
    profile:{
      type:"D2C · Healthtech",
      industry:"Skincare & Dermatology",
      subIndustry:"Dermatologist-formulated Skincare",
      model:"D2C skincare with a dermatologist consultation layer. Products sold via own website. Consultation revenue supplements product margins. Strong clinical credibility narrative.",
      stage:"Series A",
      founded:"2020",
      employees:"50–200",
      geography:"Pan-India. Primary: Mumbai, Delhi, Bengaluru. Expanding to international (UAE, UK NRI market).",
      market:"Premium clinical skincare. Consumers moving away from influencer brands toward evidence-based products. Strong tailwind from skincare education content trend.",
    },
    personas:[
      "Women 22–40 dealing with acne, pigmentation or sensitivity",
      "Skincare-educated consumers seeking dermat-backed formulations",
      "Dermatologist-referred patients continuing a prescribed routine",
      "Premium skincare buyers moving away from influencer brands",
    ],
    competitors:{
      direct:      ["Minimalist", "Dot & Key", "Plum", "The Derma Co."],
      indirect:    ["Mamaearth", "Forest Essentials", "Kama Ayurveda"],
      aspirational:["CeraVe", "Paula's Choice", "La Roche-Posay"],
    },
    products:["Retinol serums", "SPF moisturisers", "AHA/BHA exfoliants", "Vitamin C actives", "Dermat consultation add-on"],
    channels:{
      aeo:     { score:62, benchmark:52, trend:+5, gaps:3,  benchmarkSrc:"Category avg" },
      seo:     { score:71, benchmark:61, trend:+3, gaps:3,  benchmarkSrc:"Category avg" },
      meo:     { score:60, benchmark:45, trend: 0, gaps:2,  benchmarkSrc:"N/A — online only" },
      ai:      { score:65, benchmark:48, trend:+6, gaps:3,  benchmarkSrc:"Category avg" },
      reviews: { score:78, benchmark:60, trend:+2, gaps:2,  benchmarkSrc:"Category avg" },
      social:  { score:60, benchmark:55, trend:+4, gaps:2,  benchmarkSrc:"Category avg" },
    },
    issues:[
      { id:"i1", channel:"AEO", title:"'Best retinol for beginners India' (27K/mo) — not owned by DermFirst", priority:22.5, impact:9, effort:4, confidence:8, why:"This is the highest-intent query for DermFirst's core product. A well-structured guide with clinical authority signals could win both the featured snippet and the AI answer box. Competitor Minimalist currently owns this query." },
      { id:"i2", channel:"SEO", title:"Competitor Minimalist outranks on 28 of 35 shared tracked keywords", priority:18.0, impact:9, effort:5, confidence:9, why:"Systematic underperformance on shared keywords indicates a domain authority and content depth gap. Minimalist has been investing in content for longer. Closing this gap requires a sustained 6-month content programme." },
      { id:"i3", channel:"AI",  title:"Cited in Perplexity but not ChatGPT or Gemini for dermat queries", priority:14.0, impact:7, effort:3, confidence:7, why:"Partial AI citation is a fragile position. It indicates some authority signals exist but are insufficient for the larger platforms. Building 5 expert-authored, cited articles should trigger ChatGPT citations within 60–90 days." },
    ],
    openRecs:1, openTasks:0, activeProjects:4,
  },
  {
    id:"tg", name:"TerraGrow Organic", init:"TG",
    website:"terragrow.in", faavi:44,
    phase:"audit", pkg:"Starter", consultant:"Arjun Reddy",
    auditAge:91, lastScanned:"91 days ago",
    confidence:"low",
    profile:{
      type:"D2C · Agri-food",
      industry:"Organic Food & Agriculture",
      subIndustry:"Organic Produce & Farm-to-table",
      model:"Farm-to-consumer organic produce and packaged organic food. Subscription box model supplemented by individual product sales.",
      stage:"Bootstrapped",
      founded:"2020",
      employees:"10–50",
      geography:"South India primary (Bengaluru, Chennai, Hyderabad). Pan-India for packaged products.",
      market:"Organic food market growing at 25% CAGR. Urban consumers willing to pay premium for certified organic. Subscription model reduces churn.",
    },
    personas:[
      "Health and sustainability-conscious urban households",
      "Parents seeking pesticide-free produce for young children",
      "Fitness communities adopting clean eating",
      "Corporate wellness programme buyers",
    ],
    competitors:{
      direct:      ["Organic Tattva", "24 Mantra Organic", "Conscious Food"],
      indirect:    ["Nature's Basket", "Godrej Nature's Basket", "FreshToHome"],
      aspirational:["Abel & Cole", "Riverford", "Thrive Market"],
    },
    products:["Organic vegetable subscription boxes", "Certified pulses & grains", "Cold-pressed oils", "Organic spice range"],
    channels:{
      aeo:     { score:38, benchmark:52, trend:-3, gaps:7,  benchmarkSrc:"Category avg" },
      seo:     { score:46, benchmark:61, trend:-1, gaps:6,  benchmarkSrc:"Category avg" },
      meo:     { score:32, benchmark:55, trend:-2, gaps:5,  benchmarkSrc:"Local avg"    },
      ai:      { score:28, benchmark:48, trend:-4, gaps:8,  benchmarkSrc:"Category avg" },
      reviews: { score:55, benchmark:60, trend: 0, gaps:4,  benchmarkSrc:"Category avg" },
      social:  { score:44, benchmark:55, trend:+1, gaps:4,  benchmarkSrc:"Category avg" },
    },
    issues:[
      { id:"i1", channel:"Audit", title:"No baseline audit completed — client onboarded 3 months ago with no diagnostic data", priority:40.0, impact:10, effort:2, confidence:9, why:"Without an audit, all subsequent recommendations are assumptions. TerraGrow has no baseline FAAVI score, no identified gaps, no competitor benchmarks and no prioritised roadmap. Everything else is blocked on this." },
      { id:"i2", channel:"AI",  title:"Brand completely absent from all AI systems — weakest AI presence in portfolio", priority:24.0, impact:9, effort:3, confidence:7, why:"Organic food is increasingly purchased via AI-recommended discovery. TerraGrow scores 28/100 on AI presence — the weakest in the entire portfolio. With the audit pending, the full picture is unknown." },
      { id:"i3", channel:"MEO", title:"Pickup location and partner stores not listed on Google Maps", priority:20.0, impact:8, effort:2, confidence:7, why:"Subscription box services with physical pickup points lose significant local discovery without Maps presence. This is directly affecting subscriber acquisition in addressable geographic areas." },
    ],
    openRecs:11, openTasks:0, activeProjects:0,
  },
];

async function run() {
  await connectDB();
  await Client.deleteMany({});
  const docs = CLIENTS.map(c => ({ ...c, _id: c.id }));
  await Client.insertMany(docs);
  console.log(`[seed] inserted ${docs.length} clients`);
  process.exit(0);
}

run().catch(e => { console.error(e); process.exit(1); });
